#!/usr/bin/env bash

set -x
cd /jenkins/sharedlib-dev/repository
find . ! -name 'README.md' -type f -exec rm -f {} +
mkdir vars
echo "def call(){
    pipeline {
        agent any
        options {
            disableConcurrentBuilds()
        }
        stages {
            stage('Checkout') {
                steps {
                    script {
                        echo \"Hello World!\"
                    }
                }
            }
        }
    }
}" > /jenkins/sharedlib-dev/repository/vars/sharedPipeline.groovy
git init --shared=true
git config user.name autogenerated_user
git config user.email autogenerated_user@local.com
git add .
git commit -m "my first commit"
git remote add origin "ssh://git@169.254.170.4:22/git-server/repos/repository.git"
cd ..
git clone --bare repository repository.git
rm -rf git-server/repository.git
mv repository.git git-server/